apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgC9sqjjFsawFkBjosqvBNs+quBJXAZTnbzoDcx4+FLhxeKIGGvZDftcxtq8t9TuE2dylqChorF0Lcv84mWhRw+7JBMPM8p+FhAMBC2qt/zzMdQJuk6Ib9WSTdGA/8K/qi90qQIuPtfDDpKaBKBoprbsB9nZCkDKxGQV4650zfNX6As0rbYqZzqIOr6Sw7zfIjQ67KDHhZO2g3BF96q465+2NTbn/f8HEC0o4pjqMjaNFmI1VeJ9tGU3Dn5duGKlY6vGaJgTW4z+2Fxz8aSmOS8RBb9XWuJQnIpUQnJq8cLg6Xcnj0n7ddyeELdE+9zEGkEQrMw5NAku+Nuqngxv4msGDs/hEI0aAXgb8KPajy7BcEuUMfer3cvQARpJAjfjdELtxAsZqAOSAjxy1UGLvftFtRIy7JtVkufePK2kHE6xh+QCFEawhCIopVMxAUe491qfkIBh7TYazQN/cuM9yAXtVJ7VdIkFzyH+udQTTYa5GztfG2Pwz/zRN5b6MSKH47tD2gTsH1NrWhuHIOo8qei+CBLGKOtUPoKaXBtD0p043YndxElOb9hLLNR6MVsV2SGGFCOtE+5xqTd4NOJpsiLokyqWK38s7cFRqTJjCK+5VZzgizbX1Y51RvuoLYzQLtFZl2fScE7B1mVRCldevkfcjmaYmhRxJGRpKZ583Jcvl8K3x/QP9n+SbvreDtlSqwXjJG6Mcqsj4AXfmv7tG2E1EpHOHf1SMFit9K4G85O6viRD0rHyTW1B
    username: AgAJ8S1eZIWs8b+UUrxp0Qo1mlGy7MhF5OwiptGz1NgMtO5zqs+5/llNsFSBQwX1ipg1yrFuhaRtBtsNhUVAsnHkz/0aQi7m19s0xefTFqV54E9oo0cTziVULWGHgzbQXmcJ/hrgw27c+XhttsfteY/kWNdykEgWB6sAHoXcp2JMtx/z21IPh+hClHimvpMpTNDMbCLuf6dkE4CxxswYx9ftRkHrvB0q99Mtq+HS+b7Q9mt4nPBqG38i5AQ1DfgMMIBfJJv3OGk3aevEaZ23I+jCN5JwAdrlKX/v2BeqeBR5s4szJnvYKmBI5BxiFTSHZSEY/fiV/Yx0bQQIG4ICBS/WLJC39xLjh/ZlbKq0SvScy5uY+WbAmDsQZ75BCA9DEm/lB6S//q2zT2tnvep0Ziku7S0V1pRDx0UeOXnfbnSopuUP8C3uhufmI1qbbc802RcQyTNZVzh/cEF/G1VdSlgaLWbgMC/dpXXrdCPssc4awCBBgmulFJ9iWmD92FiOFsyxsZnhZMpzMySnebUtL6/95OOk+GWpas06lH6Zp57Uj9k8TKw2p1R0rYJDTDHBvELzd4VjbuWLsJP+H5/p9v8VpILprhiidGRbsuv3uKKSW0b8Yv1fzruB0oz4PiRGdHc1PaMn2IVgYz4KYddvNMXDHKMtpgS8/c6YbZUP1yn66kzauWpCFy6Tp60fa6KF95k//rsI3ZLPvs3r
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

